### ISSUE TITLE
Title numbers start from 1

### ISSUE THREAD

**Issue by kxccc** [whitestarrain/md-section-number.nvim#3]
If the minimum heading level in a Markdown document is a second-level heading (##), the inserted numbering will start from 0. Is it possible to make it start from 1 instead?

**Comment by whitestarrain** [comment]
> If the minimum heading level in a Markdown document is a second-level heading (##), the inserted numbering will start from 0. Is it possible to make it start from 1 instead?

@kxccc 
I plan to take some time to implement it recently, I also have similar usage scenarios now.
Should be easy to implement based on current code.

**Comment by whitestarrain** [comment]
@kxccc 
Please update the plugin and try this:
```lua
{
    min_level = 2, -- start to add section number after min_level
}
```
If there are no problems in use, I will close this issue.
